= IoT Demo - OpenShift

:Author:    Patrick Steiner
:Email:     psteiner@redhat.com
:Date:      15.04.2017

:toc: macro

toc::[]

== Purpose
This Demo is an updated version of the IoT Demo made of

 * https://github.com/PatrickSteiner/IoT_Demo_Datacenter[Datacenter]
 * https://github.com/PatrickSteiner/IoT_Demo_Gateway[Gateway]

The difference from this setup to the one in the repositories mentioned above is,
that this runs on https://www.redhat.com/en/technologies/cloud-computing/openshift[Red Hat OpenShift],
the Docker & Kubernetes based Container runtime environment provided by https://www.redhat.com/en[Red Hat].

== Prerequisites
This Demo assumes you have

  * access to a running https://www.redhat.com/en/technologies/cloud-computing/openshift[Red Hat OpenShift] system
  * good knowledge on https://www.redhat.com/en/technologies/cloud-computing/openshift[Red Hat OpenShift]
  * an https://www.ansible.com/[Ansible] host
  * good working knowledge of https://www.ansible.com/[Ansible]

During this instructions, I will assume you have a fresh installation of https://developers.redhat.com/products/cdk/overview/[Red Hat Container Development Kit],
but any other OpenShift V3 installation will work as well.

== Gateway
The Gateway in an IoT Architecture is responsible as

 * local access point for sensors
 * first aggregation- or filter-point for sensor data
 * "normalization" of sensor data
 * forwarding sensor data to datacenter

=== Installation of Gateway
This repository provides you with an https://www.ansible.com/[Ansible] script to
install

 * install https://access.redhat.com/documentation/en-us/red_hat_jboss_middleware_for_openshift/3/html/red_hat_jboss_fuse_integration_services_2.0_for_openshift/[RED HAT JBOSS FUSE INTEGRATION SERVICES 2.0 FOR OPENSHIFT]
 * install https://access.redhat.com/documentation/en-us/red_hat_jboss_middleware_for_openshift/3/html-single/red_hat_jboss_a-mq_for_openshift/[RED HAT JBOSS A-MQ FOR OPENSHIFT]

To install these OpenShift artefacts, please run

 $ cd Ansible
 $ ansible-playbook prepare_IoT_Demo.yml

[NOTE]
====
Depending on the performance of your OpenShift infrastructure, it might take a while
for the deployed artifacts to be really available. On my MacBook it's about 2 minutes.

To verify, you can check if the JBoss Fuse Integration Services ImageStream is
ready

 $ oc get is -n openshift
 NAME                    ...                         UPDATED
 fis-java-openshift      ...                     34 minutes ago
 fis-karaf-openshift     ...                     34 minutes ago
====

With this done, you can login to https://www.redhat.com/en/technologies/cloud-computing/openshift[Red Hat OpenShift] to
deploy the the *Gateway Code*.

 $ cd Gateway/receiver/
 $ mvn fabric8:deploy

This will install a https://access.redhat.com/documentation/en-us/red_hat_jboss_middleware_for_openshift/3/html/red_hat_jboss_fuse_integration_services_2.0_for_openshift/[RED HAT JBOSS FUSE INTEGRATION SERVICES 2.0 FOR OPENSHIFT] based
Camel route, which

 * reads Sensor data from MQTT Topics
 * convert MQTT data / topic into a XML Document
 * place XML Document into JMS Queue

With this done, the next step will install a https://www.redhat.com/en/technologies/jboss-middleware/business-rules[JBoss BRMS] based service,
which uses Complex Event Processing to filter messages with same values and to calculate an
average.

 $ oc new-app --image-stream=redhat-openjdk18-openshift --context-dir=Gateway/complexEventProcessing https://github.com/PatrickSteiner/IoT_Demo_Openshift -e AB_JOLOKIA_OFF=true -e JAVA_APP_JAR="rules_cep-jar-with-dependencies.jar" -e SOURCE_AMQ_BROKER=tcp://broker-amq-tcp:61616 -e TARGET_AMQ_BROKER=tcp://broker-amq-tcp:61616 -e SOURCE_QUEUE=message.to.rules_cep -e TARGET_QUEUE=message.to.datacenter -e BROKER_ADMIN_UID=admin -e BROKER_ADMIN_PASSWD=change12_me

If you changed anything in your setup, or want the Gateway to send processes data to some
other JMS Broker, you will have to change the following parameters

[width="80%",frame="topbot",options="header,footer"]
|==================================
| Paramter | Default | Meaning
| SOURCE_AMQ_BROKER | tcp://broker-amq-tcp:61616 | Broker from which to read the Sensordata, after it got changed from MQTT to JMS.
| TARGET_AMQ_BROKER | tcp://broker-amq-tcp:61616 | Broker to put Sensordata, after it got processed by the Complex Event Processing service.
| SOURCE_QUEUE | message.to.rules_cep | JMS Queue from which to read the Sensordata.
| TARGET_QUEUE | message.to.datacenter | JMS Queue to place the processed Sensordata to.
| BROKER_ADMIN_UID | admin | User-ID to authenticate at JMS Broker. Source- and Target-Broker need to have the same!
| BROKER_ADMIN_PASSWORD | change12_me | Password to authenticate at JMS Broker. Source- and Target-Broker need to have the same!
|==================================

=== Sending Simulated Sensordata
